src/memoria/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('memoria/', include('django.contrib.auth.urls')),
    path('memoria/', include("memoria_quiz_app.urls")),
]

src/memoria_quiz_app/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy

from memoria_quiz_app import views
from memoria_quiz_app.views import signup, SubjectEdit, SubjectChoice, QuizView
from django.contrib.auth import views as auth_views
import django.contrib.auth.urls
import django.contrib.admin.templates.registration
app_name = "memoria"

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('privacy/', views.privacy, name="privacy"),
    path('legals/', views.legals, name="legals"),
    path("account/", include("django.contrib.auth.urls")),
    path('account/signup/', signup, name="signup"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('subjects/index/', SubjectChoice.as_view(), name='index-subjects'),
    path('subjects/edit/<int:pk>', SubjectEdit.as_view(), name="edit-subjects"),
    path('subjects/quiz/<str:subject>', QuizView.as_view(), name='quiz'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html", email_template_name="registration/password_reset_email.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"), name="password_reset_complete"),

]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}?">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'memoria:home' %}">MemorIA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'memoria:home' %}">Accueil</a>
        </li>
          {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'memoria:login' %}">Connexion</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'memoria:signup' %}">Inscription</a>
        </li>
            {% endif %}
            {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'memoria:index-subjects' %}">Quiz</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'memoria:edit-subjects' pk=user.pk %}">Modifier</a>
        </li>
            {% endif %}
      </ul>
        {% if request.user.is_authenticated %}
        <span class="nav-item" id="username">
          <a class="nav-link" href="#">{{ user }}</a>
        </span>
        <span class="nav-item">
            <a class="nav-link" href="{% url 'memoria:logout' %}">Déconnexion</a>
        </span>
        {% endif %}
    </div>
  </div>
</nav>




{% for message in messages %}
{% if message.tags == 'error' %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% elif message.tags == 'success' %}
    <div class="alert alert-success" role="alert">
        {{ message }}
    </div>
    {% endif %}
{% endfor %}


<section id="memoria">
    {% block content %}
    {% endblock %}
</section>

</body>
<footer>
    <div class="footer">
        <p>© 2024 MemorIA</p>
        <a href="{% url 'memoria:about' %}">À propos</a>
        <a href="{% url 'memoria:privacy' %}">Confidentialité</a>
        <a href="{% url 'memoria:legals' %}">Mentions légales</a>
    </div>
</footer>
</html>