src/memoria/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('memoria/', include('django.contrib.auth.urls')),
    path('memoria/', include("memoria_quiz_app.urls")),
]

src/memoria_quiz_app/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy

from memoria_quiz_app import views
from memoria_quiz_app.views import signup, SubjectEdit, SubjectChoice, QuizView
from django.contrib.auth import views as auth_views
import django.contrib.auth.urls
import django.contrib.admin.templates.registration
app_name = "memoria"

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('privacy/', views.privacy, name="privacy"),
    path('legals/', views.legals, name="legals"),
    path("account/", include("django.contrib.auth.urls")),
    path('account/signup/', signup, name="signup"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('subjects/index/', SubjectChoice.as_view(), name='index-subjects'),
    path('subjects/edit/<int:pk>', SubjectEdit.as_view(), name="edit-subjects"),
    path('subjects/quiz/<str:subject>', QuizView.as_view(), name='quiz'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html", email_template_name="registration/password_reset_email.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"), name="password_reset_complete"),

]

src/memoria_quiz_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from memoria_quiz_app.models import CustomUser, Questions


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email", "first_name", "last_name", "password1", "password2",)


class UserSubjectsForm(ModelForm):

    class Meta:
        model = CustomUser
        fields = ("subject1", "difficulty_subject1", "subject2", "difficulty_subject2", "difficulty_general_culture")
        subject1 = forms.CharField(required=True, min_length=5)
        subject2 = forms.CharField(required=True, min_length=5)
        difficulty_subject1 = forms.ChoiceField(choices=CustomUser.difficulty_choices, required=True)
        difficulty_subject2 = forms.ChoiceField(choices=CustomUser.difficulty_choices, required=True)
        difficulty_general_culture = forms.ChoiceField(choices=CustomUser.difficulty_choices, required=True)
        widgets = {
            "subject1": forms.TextInput(attrs={"class": "form-control"}),
            "difficulty_subject1": forms.Select(attrs={"class": "form-control"}),
            "subject2": forms.TextInput(attrs={"class": "form-control"}),
            "difficulty_subject2": forms.Select(attrs={"class": "form-control"}),
            "difficulty_general_culture": forms.Select(attrs={"class": "form-control"}),
        }


class UserQuizForm(ModelForm):
    class Meta:
        model = Questions
        fields = ("user_answer", "is_answer_valid", "question_type",)

src/memoria_quiz_app/views.py
import ast
import datetime
import json
import logging
import os

import openai
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.decorators import method_decorator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from django.utils.translation import gettext_lazy as _
from django.views.generic import UpdateView, CreateView, ListView
from dotenv import load_dotenv

from memoria_quiz_app.forms import UserRegistrationForm, UserSubjectsForm, UserQuizForm
from .models import CustomUser, Questions
from .quiz import generate_questions, check_answer_and_scoring, user_can_play, reset_win_streak, \
    return_subject_quiz_page, reset_is_answered_question_bool, question_creation, return_subject_quiz_url
from .tokens import account_activation_token

load_dotenv()
api_key = os.getenv("OPEN_AI_KEY")
openai.api_key = api_key


# User account creation
def activate(request, uidb64, token):
    '''
    Function that activates user account when email link has been clicked on. Then redirects the user on an
    other page.
    '''
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Merci d'avoir confirmé votre email. Vous pouvez maintenant vous connecter. ")
        return redirect("memoria:login")

    messages.error(request, "Lien d'activation invalide.")
    return redirect('memoria:home')


def activateEmail(request, user, to_email):
    '''
    Function that send confirmation email to user.
    '''
    mail_subject = _("Activez votre compte")
    message = render_to_string("activate_account/template_activate_account.html", {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        'protocol': 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f"Cher {user}, veuillez vérifier votre adresse email {to_email}")
    else:
        messages.error(request, f"Problem sending email to {to_email}, check if you typed it correctly.")


def signup(request):
    context = {}
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get('email'))
            return redirect("memoria:home")
        else:
            context["form"] = form
    else:
        form = UserRegistrationForm()
        context["form"] = form

    return render(request, "memoria/signup.html", context)


# Subject choice, edit and stats
class SubjectChoice(ListView):
    model = CustomUser
    questions = Questions
    template_name = "subjects/subject_index.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = CustomUser.objects.get(pk=self.request.user.id)
        context["questions"] = Questions.objects.filter(user=context["user"]).first()
        return context


class SubjectEdit(UpdateView):
    model = CustomUser
    questions = Questions
    template_name = "subjects/subject_edit.html"
    fields = ["subject1", "difficulty_subject1", "subject2", "difficulty_subject2", "difficulty_general_culture", ]

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        current_user = request.user.id
        user_to_edit = CustomUser.objects.get(pk=self.kwargs['pk']).pk
        if current_user == user_to_edit:
            self.object = self.get_object()
            return super().get(request, *args, **kwargs)
        else:
            messages.error(request, "Erreur")
            return redirect("memoria:index-subjects")

    def post(self, request, *args, **kwargs):
        form = UserSubjectsForm(request.POST)
        user_to_edit = CustomUser.objects.get(pk=self.kwargs['pk'])
        if form.is_valid():
            old_subject1 = user_to_edit.subject1
            old_difficulty_subject1 = user_to_edit.difficulty_subject1
            old_subject2 = user_to_edit.subject2
            old_difficulty_subject2 = user_to_edit.difficulty_subject2
            old_difficulty_general_culture = user_to_edit.difficulty_general_culture
            user_to_edit.subject1 = form.cleaned_data['subject1']
            user_to_edit.subject2 = form.cleaned_data['subject2']
            user_to_edit.difficulty_subject1 = form.cleaned_data['difficulty_subject1']
            user_to_edit.difficulty_subject2 = form.cleaned_data['difficulty_subject2']
            user_to_edit.difficulty_general_culture = form.cleaned_data['difficulty_general_culture']
            reset_win_streak(user_to_edit, "subject1", user_to_edit.subject1, old_subject1)
            reset_win_streak(user_to_edit, "subject2", user_to_edit.subject2, old_subject2)
            user_to_edit.save()

            # Generate new questions if the subject has changed
            if old_subject1 != user_to_edit.subject1 or user_to_edit.subject1 is None or Questions.objects.filter(
                    is_question_answered=1,
                    user=user_to_edit).count() >= 20 or old_difficulty_subject1 != user_to_edit.difficulty_subject1:
                Questions.objects.filter(subject="subject1", user=user_to_edit).delete()
                try:
                    response_data = json.loads(
                    generate_questions(user_to_edit, "subject1", user_to_edit.difficulty_subject1))
                except Exception as e:
                    print(f"Error: {e}")
                    messages.error(request, "Erreur lors de la génération des questions.")
                    return redirect("memoria:index-subjects")
                questions_subject1 = response_data['questions']
                for question_json in questions_subject1:
                    question = question_json['question']
                    question_type = question_json['type']
                    expected_answer = question_json['answer']
                    options = question_json.get('options')
                    try:
                        explication = question_json['explanation']
                    except:
                        explication = None
                    question_creation(user_to_edit, "subject1", question, question_type, options, explication,
                                      expected_answer)

            # Generate new questions if the subject has changed
            if old_subject2 != user_to_edit.subject2 or user_to_edit.subject2 is None or Questions.objects.filter(
                    is_question_answered=1,
                    user=user_to_edit).count() >= 20 or old_difficulty_subject2 != user_to_edit.difficulty_subject2:
                Questions.objects.filter(subject="subject2", user=user_to_edit).delete()
                try:
                    response_data = json.loads(
                    generate_questions(user_to_edit, "subject2", user_to_edit.difficulty_subject2))
                except Exception as e:
                    print(f"Error: {e}")
                    messages.error(request, "Erreur lors de la génération des questions.")
                    return redirect("memoria:index-subjects")
                questions_subject2 = response_data['questions']
                for question_json in questions_subject2:
                    question = question_json['question']
                    question_type = question_json['type']
                    expected_answer = question_json['answer']
                    options = question_json.get('options')
                    try:
                        explication = question_json['explanation']
                    except:
                        explication = None
                    question_creation(user_to_edit, "subject2", question, question_type, options, explication,
                                      expected_answer)

            # Generate new questions if the there is no question in the database
            # or if the user has answered 20 questions
            if (not Questions.objects.filter(subject="general_culture",
                                            user=user_to_edit).exists() or
                    Questions.objects.filter(is_question_answered=1, user=user_to_edit).count() >= 20 or
                    old_difficulty_general_culture != user_to_edit.difficulty_general_culture):
                try:
                    response_data = json.loads(generate_questions(user_to_edit,
                                                             "general_culture",
                                                              user_to_edit.difficulty_general_culture))
                except Exception as e:
                    print(f"Error: {e}")
                    messages.error(request, "Erreur lors de la génération des questions.")
                    return redirect("memoria:index-subjects")
                questions_general_culture = response_data['questions']
                for question_json in questions_general_culture:
                    # print(question_json)

src/memoria_quiz_app/templates/subjects/subject_edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}
    <title>Modifier thème</title>
{% endblock %}


{% block content %}
    <h4>N'hésitez pas à être exhaustifs sur la précision des sujets</h4>
    <p>Utilisez plusieurs mots clés</p>
    <p class="warning_score">Attention si vous changez de thème/difficulté votre série de victoires sera remise à 0<br>La génération des questions/réponses peut prendre une minute.</p>
    {% if request.user.id == user.id %}
    <div class="form-group">
        <form method="POST" id="signupForm">
            {% csrf_token %}

            <div class="subject_title">
            <strong>Thème 1 :</strong>
            </div>
            <div class="subject_form">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="inputGroup-sizing-default-subject1">🎰</span>
                        {{ form.subject1|add_class:"form-control"|attr:"placeholder: Ex.: Sciences et technologies"|attr:"required" }}
                    </div>
                    {{ form.difficulty_subject1|add_class:"form-select" }}
            </div>

            <div class="subject_title">
            <strong>Thème 2 :</strong>
            </div>
            <div class="subject_form">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default-subject2">🎰</span>
                    {{ form.subject2|add_class:"form-control"|attr:"placeholder: Ex.: Football, Histoire,..." }}
                </div>
                {{ form.difficulty_subject2|add_class:"form-select"}}
            </div>

            <div class="subject_title">
                <strong>Culture générale : </strong> Difficulté
            </div>
            <div class="subject_form">
                {{ form.difficulty_general_culture|add_class:"form-select" }}
            </div>
            <br>
            <button class="btn btn-success" type="btnsubmit" name="btnsubmit"  id="spinner-button" style="margin-bottom: 2rem;">
              <span class="spinner-border spinner-border-sm" aria-hidden="true" id="spinner" hidden></span>
              <span role="status" id="button-text">Enregistrer</span>
            </button>
        </form>
    </div>
    {% endif %}
<script src="{% static 'js/app.js' %}">
</script>
{% endblock %}

src/memoria_quiz_app/templates/subjects/subject_index.html
{% extends 'base.html' %}

{% block title %}
    <title>Quiz</title>
{% endblock %}

{% block content %}
    <h1>Choisissez un thème</h1>
    <div class="subject" id="subject1">
        <a href="{% url 'memoria:quiz' subject='subject1' %}">
            <button type="button" class="btn btn-warning btn-lg">{{ user.subject1 }}</button>
        </a>
        <p class="win_streak">Série en cours : {{ user.win_streak_subject1 }}</p>
    </div>

    <br>

    <div class="subject" id="subject2">
        <a href="{% url 'memoria:quiz' subject='subject2' %}">
            <button type="button" class="btn btn-warning btn-lg">{{ user.subject2|truncatewords:3 }}</button>
        </a>
        <p class="win_streak">Série en cours : {{ user.win_streak_subject2 }}</p>
    </div>

    <br>

    <div class="subject" id="general_culture">
        <a href="{% url 'memoria:quiz' subject='general_culture' %}">
            <button type="button" class="btn btn-warning btn-lg">Culture Générale</button>
        </a>
        <p class="win_streak">Série en cours : {{ user.win_streak_general_culture }}</p>
    </div>
{% endblock %}